---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", echo = FALSE)

show_files <- function(pkgs) {
  paths <- rev(fs::path(fs::path_file(fs::path_dir(pkgs)), fs::path_file(pkgs)))
  cat(paths, sep = "\n")
}
```

This repository provides a CRAN-like repository to serve selected R-packages from <https://forestgeo.github.io/>. For an example see the [installation instructions of the __fgeo__ package](https://forestgeo.github.io/fgeo/#installation).

### Latest source packages

```{r}
src_pkg <- fs::dir_ls(here::here("src/contrib"), glob = "*tar.gz")
show_files(src_pkg)
```

(Earlier source packages may be archived.)

### All binary packages for windows

```{r}
bin_pkg <- fs::dir_ls(here::here("bin/windows/"), glob = "*zip", recurse = TRUE)
show_files(bin_pkg)
```

### All binary packages for macosx

```{r}
bin_pkg <- fs::dir_ls(
  here::here("bin/macosx/"), glob = "*tgz", recursive = TRUE
)
show_files(bin_pkg)
```

---

"Drat" R Archive Template created by the [drat package](https://CRAN.R-project.org/package=drat)

